version: '3.6'

services:
  proftpd:
    build: .
    ports:
      - "2222:2222"
    volumes:
      - type: bind
        source: ./home
        target: /home
    environment:
      - 'MYSQL_HOST=mysql'
      - 'MYSQL_PORT=3307'
      - 'MYSQL_DATABASE=proftpd'
      - 'MYSQL_TABLE=users'
      - 'MYSQL_USER=root'
      - 'MYSQL_PASSWORD=rootpassword'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9001:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: rootpassword

  mysql:
    image: filidorwiese/mariadb-ssl:10.5
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./schemas:/docker-entrypoint-initdb.d
